# Mod Properties
mod_id=corazonmod
mod_name=Corazon Mod
mod_license=MIT
mod_version=1.0.0
mod_authors=Corazon
mod_description=Official mod created for YouTuber Corazon

# Dependencies
minecraft_version=1.20.1
minecraft_version_range=[1.20.1, 1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)

# Mappings
mapping_channel=official
mapping_version=1.20.1
